### ISSUE TITLE
TypeError on Category

### ISSUE THREAD

**Issue by luizboaretto** [internetztube/craft-slug-equals-title#14]
```
TypeError: Argument 1 passed to internetztube\slugEqualsTitle\services\ElementStatusService::isEnabledForOverwrite() must be an instance of craft\base\Element, null given, called in /home/clientproject1/webapps/clientproject1/vendor/internetztube/craft-slug-equals-title/src/SlugEqualsTitle.php on line 71 and defined in /home/clientproject1/webapps/clientproject1/vendor/internetztube/craft-slug-equals-title/src/services/ElementStatusService.php:141
Stack trace:
#0 /home/clientproject1/webapps/clientproject1/vendor/internetztube/craft-slug-equals-title/src/SlugEqualsTitle.php(71): internetztube\slugEqualsTitle\services\ElementStatusService->isEnabledForOverwrite()
#1 [internal function]: internetztube\slugEqualsTitle\SlugEqualsTitle->internetztube\slugEqualsTitle\{closure}()
#2 /home/clientproject1/webapps/clientproject1/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#3 /home/clientproject1/webapps/clientproject1/vendor/yiisoft/yii2/base/Component.php(637): yii\base\Event::trigger()
#4 /home/clientproject1/webapps/clientproject1/vendor/craftcms/cms/src/web/View.php(1784): yii\base\Component->trigger()
#5 /home/clientproject1/webapps/clientproject1/vendor/craftcms/cms/src/web/View.php(446): craft\web\View->beforeRenderPageTemplate()
#6 /home/clientproject1/webapps/clientproject1/vendor/craftcms/cms/src/web/Controller.php(257): craft\web\View->renderPageTemplate()
#7 /home/clientproject1/webapps/clientproject1/vendor/craftcms/cms/src/controllers/CategoriesController.php(401): craft\web\Controller->renderTemplate()
#8 [internal function]: craft\controllers\CategoriesController->actionEditCategory()
#9 /home/clientproject1/webapps/clientproject1/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#10 /home/clientproject1/webapps/clientproject1/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#11 /home/clientproject1/webapps/clientproject1/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#12 /home/clientproject1/webapps/clientproject1/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#13 /home/clientproject1/webapps/clientproject1/vendor/craftcms/cms/src/web/Application.php(276): yii\base\Module->runAction()
#14 /home/clientproject1/webapps/clientproject1/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction()
#15 /home/clientproject1/webapps/clientproject1/vendor/craftcms/cms/src/web/Application.php(261): yii\web\Application->handleRequest()
#16 /home/clientproject1/webapps/clientproject1/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#17 /home/clientproject1/webapps/clientproject1/web/index.php(26): yii\base\Application->run()
#18 {main}
```

PHP version: 7.4.21
MySQL: 5.5.5
Craft edition & version: Craft Pro 3.7.11

**Comment by internetztube** [comment]
Thanks for the bug report!. It should be fixed with 1.3.2. @luizboaretto 
```
composer update internetztube/craft-slug-equals-title
```
